#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
# https://github.com/fabiocaccamo/django-admin-interface#optional-themes
python manage.py loaddata admin_interface_theme_uswds.json
python manage.py runserver_plus 0.0.0.0:8000
