# Generated by Django 3.2.11 on 2022-02-05 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Read')], default=1, help_text='The status of the item. Initially it is at the new state, users can mark it as read.')),
                ('published_at', models.DateTimeField(blank=True, help_text='The date and time at which the item was published.', null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.feed')),
            ],
            options={
                'ordering': ('-published_at', '-updated_at'),
            },
        ),
    ]
