# Generated by Django 3.2.11 on 2022-02-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='e_tag',
            field=models.CharField(blank=True, help_text='ETag and Last-Modified Headers aka `last_update_by_source_at` can be used to save resources bandwidth.', max_length=255),
        ),
    ]
