# Generated by Django 3.2.11 on 2022-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_e_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.URLField(blank=True, help_text='Feed page image url'),
        ),
    ]
