# Generated by Django 3.2.11 on 2022-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Read')], db_index=True, default=1, help_text='The status of the item. Initially it is at the new state, users can mark it as read.'),
        ),
    ]
